version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongo_db:/data/db

  #NODE
  api:
    build: .
    ports:
      - "4000:5000"
    environment:
      PORT: 5000
      DB_URL: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: { }
